In [12]:
import numpy as np
import pandas as pan

Question 1: Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [13]:
# My Vender Function.
try:
    def My_Vender(a,b,c):
        array = [[]for x in range(0,len(a))]
        z = 0
        if c == "True":
            for i in a:
                for j in range(b):
                    d = i**j
                    array[z].append(d)
                z+=1
            return array
        if c == "False":
            for i in a:
                for j in range(b):
                    d = i**(b-1-j)
                    array[z].append(d)
                z+=1
            return array

except Exception as n:         # If any error ouccred it will try to handel it.
    print('The Erorr is: ',n)

    
    
try:
    Vector = int(input('Enter the vector of matrix: '))      # Taking input from user Power vector
    Element = input('Enter comma separated list of elements eg. 1,2,3:- ')    # Taking List of number  
    while True:
        Bool = input('Enter order Matrix in acsending type "True" or for dcesending type "False":') # Taking input for 
        if Bool=='True' or Bool=='False':
            break
        else:
            print('Enter either True or False')
    List = list(map(int ,Element.split(',')))
    
    
except Exception as n:           # IN user input if user make some mistake then it try to handel it 
    print('The Erorr is : ',n)

    
finally:
    mat = My_Vender(List,Vector,Bool)
    matrix = np.mat(mat)
    print("\nThe Requried Matrix\n", '-'*20, sep = '')
    print(matrix)
    print('The Program is complete')



Enter the vector of matrix: 4
Enter comma separated list of elements eg. 1,2,3:- 1,2,3,4
Enter order Matrix in acsending type "True" or for dcesending type "False": fhfhf
Enter order Matrix in acsending type "True" or for dcesending type "False":hgfgh
Enter either True or False
Enter order Matrix in acsending type "True" or for dcesending type "False":gjhgjg
Enter either True or False
Enter order Matrix in acsending type "True" or for dcesending type "False":True

The Requried Matrix
--------------------
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
The Program is complete


Question 2:  Write a function to find moving average in an array over a window:
             Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [51]:
try :
    def moving_average(mylist, N):     # My Moving Average Function
        Window, moving_average = [0], []
        for i, x in enumerate(mylist, 1):
            Window.append(Window[i-1] + x)
            if i>=N:
                moving_ave = round(((Window[i] - Window[i-N])/N),2)
                moving_average.append(moving_ave)
        return moving_average
except Exception as n:           # If any error ouccred in avove function it will try to handel it.
    print('The Erorr is : ',n)

In [55]:
mylist = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
N = 4

result1 = moving_average(mylist,N)
print("\n The moving average is :\n",'-'*70, sep='')
print("Moving average values list: ", result1)
print("\nLength of the list l-N+1: ", len(result1))


 The moving average is :
----------------------------------------------------------------------
Moving average values list:  [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]

Length of the list l-N+1:  7


In [57]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3

result2 = moving_average(mylist,N)
print("\n The moving average is :\n",'-'*100, sep='')
print("Moving average values list: ", result2)
print("\nLength of the list l-N+1: ", len(result2))


 The moving average is :
----------------------------------------------------------------------------------------------------
Moving average values list:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]

Length of the list l-N+1:  11


In [58]:
try:
    List = input('Enter comma separated list of elements eg. 1,2,3:- ')  # Taking input List of number for program
    My_List = list(map(int ,List.split(',')))
    Window = int(input('Enter the Window of matrix: '))  # Taking input from user for Window of interval
    result3 = moving_average(My_List,Window)

except Exception as n:           # IN user input if user make some mistake then it try to handel it 
    print('The Erorr is : ',n)
        
finally :
    print("\n The moving average is :\n",'-'*100, sep='')
    print("\nMoving average values list: ", result3)
    print("\nLength of the list l-N+1: ", len(result3))

Enter comma separated list of elements eg. 1,2,3:- 8,15,22,35,38,41,55,69,73,99,117,131,151,166,182,191
Enter the Window of matrix: 3

 The moving average is :
----------------------------------------------------------------------------------------------------

Moving average values list:  [15.0, 24.0, 31.67, 38.0, 44.67, 55.0, 65.67, 80.33, 96.33, 115.67, 133.0, 149.33, 166.33, 179.67]

Length of the list l-N+1:  14


In [ ]:
8,15,22,35,38,41,55,69,73,99,117,131,151,166,182,191